SELECT HOUR, COUNT(ANIMAL_OUTS.DATETIME) AS COUNT 
FROM (
    WITH RECURSIVE CTE AS (
        SELECT 0 AS HOUR
        UNION ALL
        SELECT 1 + HOUR AS HOUR FROM CTE
        WHERE HOUR < 23
    ) SELECT * FROM CTE
) TIME
LEFT JOIN ANIMAL_OUTS ON HOUR(ANIMAL_OUTS.DATETIME) = TIME.HOUR
GROUP BY HOUR ORDER BY HOUR;